#ifndef COSMOPOLITAN_LIBC_SYSTEM_PLAINCMD_INTERNAL_H_
#define COSMOPOLITAN_LIBC_SYSTEM_PLAINCMD_INTERNAL_H_
COSMOPOLITAN_C_START_

int __plaincmd(const char *, char *, char **, int);

COSMOPOLITAN_C_END_
#endif /* COSMOPOLITAN_LIBC_SYSTEM_PLAINCMD_INTERNAL_H_ */
