#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_EFD_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_EFD_H_

#define EFD_SEMAPHORE 1
#define EFD_CLOEXEC   0x80000
#define EFD_NONBLOCK  0x800

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_EFD_H_ */
