#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_FIO_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_FIO_H_

#define FIONREAD 0x541b
#define FIONBIO  0x5421
#define FIOCLEX  0x5451
#define FIONCLEX 0x5450
#define FIOASYNC 0x5452

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_FIO_H_ */
