#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_MSYNC_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_MSYNC_H_

#define MS_ASYNC      1
#define MS_INVALIDATE 2
#define MS_SYNC       4

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_MSYNC_H_ */
