#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_POLL_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_POLL_H_

#define INFTIM     (-1)
#define POLLIN     1
#define POLLPRI    2
#define POLLOUT    4
#define POLLERR    8
#define POLLHUP    0x10
#define POLLNVAL   0x20
#define POLLRDNORM 0x40
#define POLLRDBAND 0x80
#define POLLWRNORM 0x100
#define POLLWRBAND 0x200
#define POLLRDHUP  0x2000

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_POLL_H_ */
