#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_PTY_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_PTY_H_

#define TIOCPKT_DATA       0x00
#define TIOCPKT_DOSTOP     0x01
#define TIOCPKT_FLUSHREAD  0x02
#define TIOCPKT_FLUSHWRITE 0x04
#define TIOCPKT_IOCTL      0x08
#define TIOCPKT_NOSTOP     0x10
#define TIOCPKT_START      0x20
#define TIOCPKT_STOP       0x40

#define TIOCPKT            0x5420

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_PTY_H_ */
