#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_RENAME_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_RENAME_H_

#define RENAME_NOREPLACE 1
#define RENAME_EXCHANGE  2
#define RENAME_WHITEOUT  4

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_RENAME_H_ */
