#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_RUSAGE_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_RUSAGE_H_

#define RUSAGE_SELF     0
#define RUSAGE_CHILDREN -1
#define RUSAGE_THREAD   1
#define RUSAGE_BOTH     -2

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_RUSAGE_H_ */
