#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_SA_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_SA_H_

#define SA_NOCLDSTOP 1u
#define SA_NOCLDWAIT 2u
#define SA_SIGINFO   4u
#define SA_ONSTACK   0x08000000u
#define SA_RESTART   0x10000000u
#define SA_NODEFER   0x40000000u
#define SA_RESETHAND 0x80000000u

/* compatibility constants */
#define SA_NOMASK  SA_NODEFER
#define SA_ONESHOT SA_RESETHAND

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_SA_H_ */
