#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_TFD_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_TFD_H_

#define TFD_CLOEXEC             0x80000
#define TFD_NONBLOCK            0x800
#define TFD_TIMER_ABSTIME       1
#define TFD_TIMER_CANCEL_ON_SET 2

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_TFD_H_ */
