#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_

#define UTIME_NOW  0x3fffffff
#define UTIME_OMIT 0x3ffffffe

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_UTIME_H_ */
