#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_WAITID_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_WAITID_H_

#define WSTOPPED 2
#define WEXITED  4
#define WNOWAIT  0x01000000

#define P_ALL   0
#define P_PID   1
#define P_PGID  2
#define P_PIDFD 3

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_WAITID_H_ */
